properties:
  amplitude:
    dist: uniform
    dist_params:
    - 1
    - 50
    change: False

  frequency:
    dist: uniform
    dist_params:
    - 1
    - 10
    change: False

  variance:
    dist: uniform
    dist_params:
    - 0.3
    - 0.8
    change: False

  mean:
    dist: uniform
    dist_params:
    - 5
    - 8
    change: True

# Properties of the changepoint
changepoint:
  stepped: True
  location: 250
  order: 1

# Data config 
data_config:
  oscillating: False
  n_datapoints: 500
  n_datasets: 100
  time_range:
  - 0
  - 1
