amplitude_dist:
  dist: uniform
  dist_params:
  - 0
  - 100
change_type: perturbation
frequency_dist:
  dist: uniform
  dist_params:
  - 0
  - 100
glob_noise_dist: norm
glob_noise_params:
- 0
- 1
location: 130
n_datapoints: 500
n_datasets: 10
noise_dist:
  dist: uniform
  dist_params:
  - 0
  - 100
oscillating: true
perturbation_dist:
  dist: norm
  dist_params:
  - 0
  - 10
stepped: true
time_range:
- 0
- 1
